Am17072020
OWASP/owasp-masvs pull request #486
Opened 2020-08-31 16:54 UTC by MotinhaAna

Thank you for submitting a Pull Request to the Mobile Application Security Verification Standard. Please make sure that:

- [ ] Your PR is linked to an issue.
- [ ] Your PR follows the [contribution guidelines](https://github.com/OWASP/owasp-masvs/blob/master/CONTRIBUTING.md "Contribution guidelines")
- [ ] All links are valid and use HTTPS and have been formatted as [TEXT](URL “NAME”)
- [ ] In case of a translation: have you made sure that the translation from EN is as close to the EN document as possible?

This PR covers issue #< insert number here >.

If your pull-request has a focus of rewriting a requirement and/or adding a new one, please make sure you have a backing issue in which your change has been discussed and agreed. If there is none, then your PR will be closed without further review.

2020-09-23 23:28 UTC, sushi2k commented
Hi @luisfontes19. Can you please do a QA on this so we can merge it? Thanks

2020-09-24 19:03 UTC, luisfontes19 requested changes
https://owasp.org/www-project-mobiletop-10/2016-risks/m10-extraneous-functionality is down, check if it was already replaced in recent commits


There are a few comments without suggestions, so be sure to go through them 😊

2020-09-24 19:03 UTC, luisfontes19 commented on Document-ptpt/0x07-V2-Data_Storage_and_Privacy_requirements.md
You need to remove this line (markdown linter)

2020-10-03 00:50 UTC, sushi2k commented
Hi @luisfontes19. Can you please check if everything is fixed and approve if ready? Thanks

2020-10-03 12:52 UTC, luisfontes19 commented
there are still two suggested changes pending an action...
@MotinhaAna can you check them?

2020-11-07 23:26 UTC, sushi2k commented
Hi @MotinhaAna. Thanks for the PR! Can you please have a look at the suggestions that are pending?

2020-11-13 11:56 UTC, luisfontes19 approved these changes

2020-11-13 11:59 UTC, sushi2k approved these changes
Thanks everybody for the PR!

2020-11-13 12:00 UTC, merged