FInal checks for PT-PT Translation
OWASP/owasp-masvs pull request #497
Opened 2020-11-22 17:57 UTC by luisfontes19

Thank you for submitting a Pull Request to the Mobile Application Security Verification Standard. Please make sure that:

- [ ] Your PR is linked to an issue.
- [ ] Your PR follows the [contribution guidelines](https://github.com/OWASP/owasp-masvs/blob/master/CONTRIBUTING.md "Contribution guidelines")
- [ ] All links are valid and use HTTPS and have been formatted as [TEXT](URL “NAME”)
- [ ] In case of a translation: have you made sure that the translation from EN is as close to the EN document as possible?

This PR covers issue #< insert number here >.

If your pull-request has a focus of rewriting a requirement and/or adding a new one, please make sure you have a backing issue in which your change has been discussed and agreed. If there is none, then your PR will be closed without further review.

2020-11-23 11:48 UTC, sushi2k requested changes
One thing should be changed. Otherwise looks good to me :-)

2020-11-23 11:48 UTC, sushi2k commented on Document-ptpt/0x12-V7-Code_quality_and_build_setting_requirements.md
> +# V7: Requisitos de Qualidade de Codigo e DistribuiçãoRequisitos de Qualidade de Codigo e Configuração de Distribuição
```suggestion
# V7: Requisitos de Qualidade de Codigo e Distribuição
```

2020-11-23 12:53 UTC, luisfontes19 commented on Document-ptpt/0x12-V7-Code_quality_and_build_setting_requirements.md
> +# V7: Requisitos de Qualidade de Codigo e DistribuiçãoRequisitos de Qualidade de Codigo e Configuração de Distribuição
nice catch

2020-12-23 09:08 UTC, sushi2k approved these changes
Awesome work @luisfontes19! Thanks for the support and the final touches in this PR! Apologies for the late response, but was a busy month....

2020-12-23 09:08 UTC, merged