Updated ARCH links with a new link to NIST SP 800-57
OWASP/owasp-masvs pull request #509
Opened 2021-04-06 13:05 UTC by julepka

Updated the link to NIST SP 800-57. Now it points not to the exact version but the `/final` one. It should not get outdated as fast as previous links. 

- [x] Your PR is linked to an issue.
- [x] Your PR follows the [contribution guidelines](https://github.com/OWASP/owasp-masvs/blob/master/CONTRIBUTING.md "Contribution guidelines")
- [ ] All links are valid and use HTTPS and have been formatted as [TEXT](URL “NAME”) - _I think it will not be consistent to do that_

This PR covers issue #501 .

2021-04-06 19:25 UTC, cpholguera commented
Thanks @julepka!

FYI I've changed the text above to be: "This PR closes #501 ."
"closes" + issue ID acts as a magic keyword. You can see the Issue now linked in the right side of the page and once we merge the issue will be automatically closed ;)

Feel free to keep using that :)

2021-04-06 19:28 UTC, cpholguera requested changes
Could you please fix it for all other languages? Thanks in advance!

https://github.com/OWASP/owasp-masvs/search?q=sp800-57-Part1-revised2_Mar08-2007&type=

2021-04-07 08:57 UTC, julepka commented on Document-zhtw/0x06-V1-Architecture_design_and_threat_modelling_requireme.md
> +- security.txt - <https://securitytxt.org/>
I've noticed that zhtw translation is missing this link that is present in all other languages, so, I've added it as well

2021-04-07 10:24 UTC, cpholguera approved these changes
Thank you very much again @julepka!

2021-04-07 10:25 UTC, merged