Turkish translation
OWASP/owasp-masvs pull request #561
Opened 2021-11-02 07:50 UTC by haktanemik

Thank you for submitting a Pull Request to the Mobile Application Security Verification Standard. Please make sure that:

- [X] Your PR is linked to an issue.
- [X] Your PR follows the [contribution guidelines](https://github.com/OWASP/owasp-masvs/blob/master/CONTRIBUTING.md "Contribution guidelines")
- [X] All links are valid and use HTTPS and have been formatted as [TEXT](URL “NAME”)
- [X] In case of a translation: have you made sure that the translation from EN is as close to the EN document as possible?

This PR covers issue #560 .

If your pull-request has a focus of rewriting a requirement and/or adding a new one, please make sure you have a backing issue in which your change has been discussed and agreed. If there is none, then your PR will be closed without further review.

2021-11-02 17:50 UTC, cpholguera approved these changes
This is awesome @haktanemik! What an excellent surprise. Thanks to your contribution we cover now 14 languages 🎉 

Thank you very much for the hard work, once we merge it we will announce it on Twitter, LinkedIn and Slack. Would you like us to mention you directly? If yes, please send us your handles for the different platforms.

2021-11-02 18:24 UTC, haktanemik commented
Hi @cpholguera,

Thanks a lot for fast and kind your response. We would be very pleased if you mention about us. We made this translation with my friend Anıl.

Twitter usernames are @haktanemik and @0x4n1l
Linkedin usernames are @haktanemik and @anilbas1

Thank you very much.

2021-11-02 18:31 UTC, cpholguera commented
That's awesome, we will definitely mention you both!

The process goes like this: now we require a second approval from an independent target language speaker. We're currently searching for one. After that we'll merge and announce :)

Meanwhile I just need you to do one little thing. Could you please `git pull origin master` and then `git push`. I've fixed the linting and URL checking errors and with this your PR will show all green. Thanks in advance!

And thanks a lot to Anıl as well!

2021-11-03 12:09 UTC, Glassware123 commented
Hi @cpholguera,

I've fixed markdown issues. Thanks in advance!

Regards,
Anıl

2023-01-27 22:05 UTC, cpholguera requested changes

2023-01-27 22:05 UTC, cpholguera commented on Document-tr/0x01-Foreword.md
> +Bernhard Mueller tarafından
```suggestion
Bernhard Mueller tarafından

```

2023-01-27 22:05 UTC, cpholguera commented on Document-tr/0x02-Frontispiece.md
> +Ardından, sponsorlukları için OWASP Körfez Bölgesi Bölümüne teşekkür ederiz. Son olarak, kitabı [Leanpub'dan](https://leanpub.com/mobile-security-testing-guide) alan ve bize sponsor olan herkese teşe
```suggestion
Ardından, sponsorlukları için OWASP Körfez Bölgesi Bölümüne teşekkür ederiz. Son olarak, kitabı [Leanpub'dan](https://leanpub.com/mobile-security-testing-guide) alan ve bize sponsor olan herkese teşekkür ederiz.

```

2023-01-27 22:05 UTC, cpholguera commented on Document-tr/0x03-Using_the_MASVS.md
> +- Uygulama içi satın alımları olan uygulamalar, ücretli içeriği korumak için ideal olarak sunucu tarafı ve MASVS-L2 kontrollerini kullanmalıdır. Ancak, sunucu tarafı korumasını kullanma olanağının ol
```suggestion
- Uygulama içi satın alımları olan uygulamalar, ücretli içeriği korumak için ideal olarak sunucu tarafı ve MASVS-L2 kontrollerini kullanmalıdır. Ancak, sunucu tarafı korumasını kullanma olanağının olmadığı durumlar olabilir. Bu durumlarda, tersine mühendislik ve/veya kurcalama çabasını artırmak için MASVS-R kontrolleri ek olarak uygulanmalıdır.

```

2023-01-27 22:05 UTC, cpholguera commented on Document-tr/0x04-Assessment_and_Certification.md
> +MASVS, güvenli mobil uygulamaların özelliklerini tanımlamak için de kullanılabilir. Çoğu "güvenli kodlama" kursu, üstünkörü bir şekilde kodlama ipuçlarına değinerek basitçe etik bilgisayar korsanlığı
```suggestion
MASVS, güvenli mobil uygulamaların özelliklerini tanımlamak için de kullanılabilir. Çoğu "güvenli kodlama" kursu, üstünkörü bir şekilde kodlama ipuçlarına değinerek basitçe etik bilgisayar korsanlığı kurslarıdır. Bu, geliştiricilere yardımcı olmaz. Bunun yerine, güvenli geliştirme kursları örneğin en sık karşılaşılan 10 kod güvenlik bulgusuna odaklanmak yerine MASVS'de belgelenen proaktif kontrollere güçlü bir odaklanma ile MASVS'yi kullanabilir.

```

2023-01-27 22:05 UTC, cpholguera commented on Document-tr/0x06-V1-Architecture_design_and_threat_modelling_requireme.md
> +- security.txt - <https://securitytxt.org/>
```suggestion
- security.txt - <https://securitytxt.org/>

```

2023-01-27 22:05 UTC, cpholguera commented on Document-tr/0x07-V2-Data_Storage_and_Privacy_requirements.md
> +- CWE 922 (Insecure Storage of Sensitive Information) - <https://cwe.mitre.org/data/definitions/922.html>
```suggestion
- CWE 922 (Insecure Storage of Sensitive Information) - <https://cwe.mitre.org/data/definitions/922.html>

```

2023-01-27 22:05 UTC, cpholguera commented on Document-tr/0x08-V3-Cryptography_Verification_Requirements.md
> +- CWE 338 (Use of Cryptographically Weak Pseudo Random Number Generator (PRNG)) - <https://cwe.mitre.org/data/definitions/338.html>
```suggestion
- CWE 338 (Use of Cryptographically Weak Pseudo Random Number Generator (PRNG)) - <https://cwe.mitre.org/data/definitions/338.html>

```

2023-01-27 22:05 UTC, cpholguera commented on Document-tr/0x09-V4-Authentication_and_Session_Management_Requirements.md
> +- CWE 613 (Insufficient Session Expiration) - <https://cwe.mitre.org/data/definitions/613.html>
```suggestion
- CWE 613 (Insufficient Session Expiration) - <https://cwe.mitre.org/data/definitions/613.html>

```

2023-01-27 22:05 UTC, cpholguera commented on Document-tr/0x10-V5-Network_communication_requirements.md
> +- CWE 941 (Incorrectly Specified Destination in a Communication Channel) - <https://cwe.mitre.org/data/definitions/941.html>
```suggestion
- CWE 941 (Incorrectly Specified Destination in a Communication Channel) - <https://cwe.mitre.org/data/definitions/941.html>

```

2023-01-27 22:05 UTC, cpholguera commented on Document-tr/0x11-V6-Interaction_with_the_environment.md
> +- CWE 939 (Improper Authorization in Handler for Custom URL Scheme) - <https://cwe.mitre.org/data/definitions/939.html>
```suggestion
- CWE 939 (Improper Authorization in Handler for Custom URL Scheme) - <https://cwe.mitre.org/data/definitions/939.html>

```

2023-01-27 22:05 UTC, cpholguera commented on Document-tr/0x12-V7-Code_quality_and_build_setting_requirements.md
> +- CWE 937 (OWASP Top Ten 2013 Category A9 - Using Components with Known Vulnerabilities) - <https://cwe.mitre.org/data/definitions/937.html>
```suggestion
- CWE 937 (OWASP Top Ten 2013 Category A9 - Using Components with Known Vulnerabilities) - <https://cwe.mitre.org/data/definitions/937.html>

```

2023-01-27 22:05 UTC, cpholguera commented on Document-tr/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md
> +- OWASP Reverse Engineering and Code Modification Prevention - <https://wiki.owasp.org/index.php/OWASP_Reverse_Engineering_and_Code_Modification_Prevention_Project>
```suggestion
- OWASP Reverse Engineering and Code Modification Prevention - <https://wiki.owasp.org/index.php/OWASP_Reverse_Engineering_and_Code_Modification_Prevention_Project>

```

2023-01-27 22:05 UTC, cpholguera commented on Document-tr/0x90-Appendix-A_Glossary.md
> +- **X.509 Certificate** – X.509 sertifikası, genel anahtarın sertifikada bulunan kullanıcıya, bilgisayara veya hizmet kimliğine ait olduğunu doğrulamak için yaygın olarak kabul edilen uluslararası X.
```suggestion
- **X.509 Certificate** – X.509 sertifikası, genel anahtarın sertifikada bulunan kullanıcıya, bilgisayara veya hizmet kimliğine ait olduğunu doğrulamak için yaygın olarak kabul edilen uluslararası X.509 genel anahtar altyapısı (PKI) standardını kullanan dijital bir sertifikadır.

```

2023-01-27 22:05 UTC, cpholguera commented on Document-tr/0x91-Appendix-B_References.md
> +- PCI Data Security Standard (DSS) v3.0 Requirements and Security Assessment Procedures - [https://www.pcisecuritystandards.org/documents/PCI\_DSS\_v3.pdf](https://www.pcisecuritystandards.org/docume
```suggestion
- PCI Data Security Standard (DSS) v3.0 Requirements and Security Assessment Procedures - [https://www.pcisecuritystandards.org/documents/PCI\_DSS\_v3.pdf](https://www.pcisecuritystandards.org/documents/PCI_DSS_v3.pdf)

```

2023-01-27 22:05 UTC, cpholguera commented on Document-tr/CHANGELOG.md
> +- Küçük düzeltmeler (yazım hataları vb.)
```suggestion
- Küçük düzeltmeler (yazım hataları vb.)

```

2023-01-27 22:05 UTC, cpholguera commented on Document-tr/GLOSSARY.md
> +X.509 sertifikası, genel anahtarın sertifikada bulunan kullanıcıya, bilgisayara veya hizmet kimliğine ait olduğunu doğrulamak için yaygın olarak kabul edilen uluslararası X.509 genel anahtar altyapıs
```suggestion
X.509 sertifikası, genel anahtarın sertifikada bulunan kullanıcıya, bilgisayara veya hizmet kimliğine ait olduğunu doğrulamak için yaygın olarak kabul edilen uluslararası X.509 genel anahtar altyapısı (PKI) standardını kullanan dijital bir sertifikadır.

```

2023-01-27 22:05 UTC, cpholguera commented on Document-tr/SUMMARY.md
> +- [Ek B: Referanslar](0x91-Appendix-B_References.md)
```suggestion
- [Ek B: Referanslar](0x91-Appendix-B_References.md)

```

2023-01-27 22:12 UTC, cpholguera approved these changes
Excellent work @haktanemik! And apologies for the delay. We were focusing on the MASVS refactoring as you might know. Thank you very much!

2023-01-27 22:24 UTC, merged

2023-01-30 08:02 UTC, Glassware123 commented
Hi @cpholguera,

Thanks for great news! Have a nice day.

Best regards.