Feature/issue643 improve spanish translation
OWASP/owasp-masvs pull request #645
Opened 2022-06-08 09:17 UTC by Sulfkain

Improve translation to simplify the language and coordinate number and gender
Improve comprehension adding the number of chapters
Change names to be the same as on other part of the doc.

Thank you for submitting a Pull Request to the Mobile Application Security Verification Standard. Please make sure that:

- [x] Your PR is linked to an issue.
- [x] Your PR follows the [contribution guidelines](https://github.com/OWASP/owasp-masvs/blob/master/CONTRIBUTING.md "Contribution guidelines")
- [x] All links are valid and use HTTPS and have been formatted as [TEXT](URL “NAME”)
- [x] In case of a translation: have you made sure that the translation from EN is as close to the EN document as possible?

This PR covers issue #<643>.

If your pull-request has a focus of rewriting a requirement and/or adding a new one, please make sure you have a backing issue in which your change has been discussed and agreed. If there is none, then your PR will be closed without further review.

2022-06-11 08:23 UTC, cpholguera requested changes
Thanks for the corrections @Sulfkain, I've included a couple of suggestions. If you like them you can click to commit them, else feel free to discuss further by answering.

2022-06-11 08:23 UTC, cpholguera commented on Document-es/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md
> +Para que los controles de la lista siguiente sean eficaces, la aplicación debe cumplir todos los requerimientos del nivel MASVS-L1 (es decir, deben existir sólidos controles de seguridad), así como t
```suggestion
Para que los controles de la lista siguiente sean eficaces, la aplicación debe cumplir todos los requerimientos del nivel MASVS-L1 (es decir, deben existir sólidos controles de seguridad), así como todos los requerimientos de V8. Por ejemplo, los controles de ofuscación listados en la sección ["Impedir la comprensión"](#impedir-la-comprensión) (8.11 y 8.12) deben combinarse con los de ["Impedir el análisis dinámico y la manipulación"](#impedir-el-análisis-dinámico-y-la-manipulación) (8.1 - 8.9) y ["Asociación del dispositivo"](#asociación-del-dispositivo) (8.10).
```

2022-06-11 08:23 UTC, cpholguera commented on Document-es/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md
> +1. Debe definirse un modelo de amenaza que defienda claramente las amenazas del lado del cliente. Además, debe especificarse el grado de protección que debe proporcionar el sistema. Por ejemplo, un o
```suggestion
1. Debe definirse un modelo de amenaza que defienda claramente las amenazas del lado del cliente. Además, debe especificarse el grado de protección que debe proporcionar el sistema. Por ejemplo, un objetivo podría ser forzar a los autores de malware pensado para obtener información de la aplicación, a que tengan que invertir importantes esfuerzos para realizar la ingeniería inversa.
```

2022-06-11 08:23 UTC, cpholguera commented on Document-es/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md
> +3. La eficacia de la protección siempre debe ser verificada por un experto con experiencia en el testeo y uso de tipos específicos de anti-manipulación y ofuscación (ver también los capítulos "Ingeni
```suggestion
3. La eficacia de la protección siempre debe ser verificada por un experto con experiencia en el testeo y uso de tipos específicos de anti-manipulación y ofuscación (ver también el capítulo ["Ingeniería Inversa y Manipulación de Aplicaciones Móviles"](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x04c-Tampering-and-Reverse-Engineering.md) en la Guía de Pruebas de Seguridad Móvil (OWASP MSTG).
```

2022-06-11 08:23 UTC, cpholguera commented on Document-es/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md
> +En esta sección se cubren las protecciones recomendadas para aplicaciones que manejan o brindan acceso a información o funcionalidades sensibles. La falta de estos controles no generan vulnerabilidad
```suggestion
En esta sección se cubren las protecciones recomendadas para aplicaciones que manejan o dan acceso a información o funcionalidades sensibles. La falta de estos controles no implica necesariamente que la aplicación contenga vulnerabilidades. Estos controles están pensados para incrementar la resistencia contra la ingeniería inversa, dificultando al adversario el acceso a los datos o el entendimiento del funcionamiento interno de la aplicación.
```

2022-06-11 08:23 UTC, cpholguera commented on Document-es/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md
> +Los controles de esta sección deben aplicarse según sea necesario, basándose en una evaluación de los riesgos causados por la manipulación no autorizada de la aplicación y/o la ingeniería inversa del
```suggestion
Los controles de esta sección deben aplicarse según sea necesario, basándose en una evaluación de los riesgos causados por la manipulación no autorizada de la aplicación y/o la ingeniería inversa del código. Sugerimos consultar el documento de OWASP ["Riesgos técnicos de la Ingeniería Inversa y Modificaciones de Código no Autorizadas"](https://wiki.owasp.org/index.php/Technical_Risks_of_Reverse_Engineering_and_Unauthorized_Code_Modification) para obtener una lista de los riesgos de negocio, así como las amenazas técnicas asociadas.
```

2022-06-13 06:18 UTC, Sulfkain commented on Document-es/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md
> +Para que los controles de la lista siguiente sean eficaces, la aplicación debe cumplir todos los requerimientos del nivel MASVS-L1 (es decir, deben existir sólidos controles de seguridad), así como t
The new links seems a great idea to me! 👏 

The "anteriores" I think is much better explained before, due without it, you just seems to say you need to achieve all V8, no just de previous from you want to implement. and without it, it will violate the rule of the PR's
"In case of a translation: have you made sure that the translation from EN is as close to the EN document as possible?"

"los de" seems great too.

2022-06-13 06:35 UTC, Sulfkain commented on Document-es/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md
> +3. La eficacia de la protección siempre debe ser verificada por un experto con experiencia en el testeo y uso de tipos específicos de anti-manipulación y ofuscación (ver también los capítulos "Ingeni
It lefts one ")" to close the "(ver también....)"

Maybe replace "(ver también.... (OWASP MSTG)" for:

La eficacia de la protección siempre debe ser verificada por un experto con experiencia en el testeo y uso de tipos específicos de anti-manipulación y ofuscación.
_Ver también el capítulo ["Ingeniería Inversa y Manipulación de Aplicaciones Móviles"](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x04c-Tampering-and-Reverse-Engineering.md) en la Guía de Pruebas de Seguridad Móvil (OWASP MSTG)._

We quit () and replace with a full complete phrase anex to the first one.

2022-06-13 21:16 UTC, cpholguera commented on Document-es/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md
> +3. La eficacia de la protección siempre debe ser verificada por un experto con experiencia en el testeo y uso de tipos específicos de anti-manipulación y ofuscación (ver también los capítulos "Ingeni
Nicely seen and I like your suggestion. I've corrected it, you may click now on "commit suggestion".

2022-06-13 21:22 UTC, cpholguera commented on Document-es/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md
> +Para que los controles de la lista siguiente sean eficaces, la aplicación debe cumplir todos los requerimientos del nivel MASVS-L1 (es decir, deben existir sólidos controles de seguridad), así como t
Thank you for being so considerate of avoiding any violations of the translation and keeping the original meaning. I really appreciate that.

Let me investigate this specific case and I'll come back to you, this is a bit weird, even in the English version.. something doesn't really click for me.

2022-06-16 16:46 UTC, cpholguera requested changes
Hi @Sulfkain,

there's one correction to make, could you please take a look?

Also, we really discourage from merging other PRs branches into your own. If you could please undo the merge of the "v8" branch that'd be very helpful and I will be able to merge your PR sooner actually.

You can leave the affected paragraph as it was, don't worry it will disappear once I merge the other PR.

Thank you very much!

2022-06-16 16:46 UTC, cpholguera commented on Document-es/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md
> +1. Debe definirse un modelo de amenaza que defiende claramente las amenazas del lado del cliente. Además, debe especificarse el grado de protección que debe proporcionar el sistema. Por ejemplo, un o
"defienda" was already right. Could you please correct it? Thank you!

2022-06-17 06:56 UTC, Sulfkain commented on Document-es/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md
> +1. Debe definirse un modelo de amenaza que defiende claramente las amenazas del lado del cliente. Además, debe especificarse el grado de protección que debe proporcionar el sistema. Por ejemplo, un o
I missunderstood then the phrase 
>> we'll merge it soon and you can update yours with it: https://github.com/OWASP/owasp-masvs/pull/646"

I have undo the merge, but was as a normal commit that i think will cause merge problem later :/
I you need anything (maybe a new branch/PR without intermediate commits) just tell me.

2022-06-17 10:12 UTC, cpholguera commented on Document-es/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md
> +Para que los controles de la lista siguiente sean eficaces, la aplicación debe cumplir todos los requerimientos del nivel MASVS-L1 (es decir, deben existir sólidos controles de seguridad), así como t
Hi @Sulfkain, I've missed this message unfortunately. Sorry about that.

I'm checking and I can't find any message or mention, do you have a link?

However, please notice that the OWASP Mobile Top 10 is a completely separate project from the OWASP MASVS and MSTG. It has its own leaders which you may want to contact instead:

https://owasp.org/www-project-mobile-top-10/

Milan Singh Thakur: milan@owasp.org
Jonathan Carter: jonathan.carter@owasp.org

2022-06-17 10:20 UTC, cpholguera commented on Document-es/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md
> +1. Debe definirse un modelo de amenaza que defiende claramente las amenazas del lado del cliente. Además, debe especificarse el grado de protección que debe proporcionar el sistema. Por ejemplo, un o
```suggestion
1. Debe definirse un modelo de amenaza que defienda claramente las amenazas del lado del cliente. Además, debe especificarse el grado de protección que debe proporcionar el sistema. Por ejemplo, un objetivo podría ser forzar a los autores de malware pensado para obtener información de la aplicación, a que tengan que invertir importantes esfuerzos para realizar la ingeniería inversa.
```

2022-06-17 10:21 UTC, cpholguera approved these changes
Thank you very much again for fixing all of this @Sulfkain. I'll be looking forward to other PRs from you! We're ready to go here :)

2022-06-17 10:24 UTC, cpholguera commented on Document-es/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md
> +1. Debe definirse un modelo de amenaza que defiende claramente las amenazas del lado del cliente. Además, debe especificarse el grado de protección que debe proporcionar el sistema. Por ejemplo, un o
Thanks for undoing the merge that helps a lot.

2022-06-17 10:26 UTC, merged

2022-06-17 10:37 UTC, Sulfkain commented
> Thank you very much again for fixing all of this @Sulfkain. I'll be looking forward to other PRs from you! We're ready to go here :)

Thank you to this wonderfull project ;) great job!

2022-06-17 10:47 UTC, cpholguera commented
Are you aware of the refactoring that we're performing?

https://github.com/OWASP/owasp-masvs/discussions/553


We did our last talk on this recently, no recording yet but you can take a look at the slides here: https://twitter.com/OWASP_MSTG/status/1536263069503987713?t=7Nh_z3eDkHJqjAJfA9ig7Q&s=19

We'll need translation help in a couple of months, the whole MASVS will change in its V2.0. If this is interesting for you we'll be happy to have you with us :)

2022-06-20 08:35 UTC, Sulfkain commented
> Are you aware of the refactoring that we're performing?
> 
> #553
> 
> Here's an introduction:
> 
> https://youtu.be/DFkCiNE2-MY
> 
> We did our last talk on this recently, including updates and a lot of insight into the process and how the changes came to be. There's no recording yet but you can take a look at the slides here: https://twitter.com/OWASP_MSTG/status/1536263069503987713?t=7Nh_z3eDkHJqjAJfA9ig7Q&s=19
> 
> We'll need translation help in a couple of months, the whole MASVS will change in its V2.0. If this is interesting for you we'll be happy to have you with us :)

Wow, the v2 seems great to me, I will check all the things I have seen to improve v1, because I see too some steps been similar to each others and could be merged.

The translation of v2 will be hard for a matter of free time, but I will try it but I don't promise to be able then.

Thank's for this great project.