Issue643
OWASP/owasp-masvs pull request #658
Opened 2022-08-17 23:51 UTC by antoniojturel

Thank you for submitting a Pull Request to the Mobile Application Security Verification Standard. Please make sure that:

- [ ] Your PR is linked to an issue.
- [ ] Your PR follows the [contribution guidelines](https://github.com/OWASP/owasp-masvs/blob/master/CONTRIBUTING.md "Contribution guidelines")
- [ ] All links are valid and use HTTPS and have been formatted as [TEXT](URL “NAME”)
- [ ] In case of a translation: have you made sure that the translation from EN is as close to the EN document as possible?

This PR covers issue #643 .

If your pull-request has a focus of rewriting a requirement and/or adding a new one, please make sure you have a backing issue in which your change has been discussed and agreed. If there is none, then your PR will be closed without further review.

2022-08-27 09:29 UTC, cpholguera requested changes
Hi @antoniojturel, thank you very much for taking the time to do this corrections. I think it's a very nice choice to use "requisitos" and you've made the controls sound more native like, which is not always easy.

Please take a look at the suggestions. If you agree with them you can either click on "Commit suggestion" one by one or "Add suggestion to batch" and then commit once at the end.

Thank you!

2022-08-27 09:29 UTC, cpholguera commented on Document-es/0x01-Foreword.md
> +Además, la aparición del malware y las herramientas de administración remota han concienciado en que los propios sistemas operativos móviles tienen vulnerabilidades explotables, por lo que las estrat
```suggestion
Además, la aparición del malware y las herramientas de administración remota han conseguido promover una mayor conciencia pública de que los propios sistemas operativos móviles tienen vulnerabilidades explotables, por lo que las estrategias de aislamiento se utilizan cada vez más para proporcionar protección adicional a los datos confidenciales y evitar la manipulación en el lado del cliente. Aquí es donde las cosas se complican. Las características de seguridad por hardware y las soluciones de aislamiento a nivel de sistema operativo, como _Android for Work_ y Samsung Knox, existen, pero no siempre están disponibles en diferentes dispositivos. Es posible implementar medidas de protección basadas en software a modo de parches - pero desafortunadamente, no hay estándares o procesos de prueba para verificar este tipo de protecciones.
```

2022-08-27 09:29 UTC, cpholguera commented on Document-es/0x01-Foreword.md
> +Como resultado, los informes de pruebas de seguridad de aplicaciones móviles están por todas partes: Por ejemplo, algunos reportan una falta de ofuscación o detección de _root_ en una aplicación Andr
```suggestion
Como resultado, los informes de pruebas de seguridad de aplicaciones móviles están por todas partes: por ejemplo, algunos reportan una falta de ofuscación o detección de _root_ en una aplicación Android como "fallo de seguridad". Por otra parte, las medidas como el cifrado de _strings_, la detección de depuradores o la ofuscación del flujo de control no se consideran obligatorias. Sin embargo, esta forma binaria de ver las cosas no tiene sentido porque la resistencia no es una proposición binaria sino que depende de las amenazas particulares en el dispositivo contra las que se quiere defender. Las protecciones de software no son inútiles, pero en última instancia pueden ser eludidas, por lo que nunca deben utilizarse como sustituto de los controles de seguridad.
```

2022-08-27 09:29 UTC, cpholguera commented on Document-es/0x01-Foreword.md
> +El objetivo general del MASVS es ofrecer tanto una línea de base para la seguridad de las aplicaciones móviles (MASVS-L1) como también la inclusión de medidas de defensa en profundidad (MASVS-L2) y p
```suggestion
El objetivo general del MASVS es ofrecer tanto una línea base de referencia para la seguridad de las aplicaciones móviles (MASVS-L1) como también la inclusión de medidas de defensa en profundidad (MASVS-L2) y protecciones contra las amenazas del lado del cliente (MASVS-R). El MASVS está pensado para lograr lo siguiente:
```

2022-08-27 09:29 UTC, cpholguera commented on Document-es/0x03-Using_the_MASVS.md
> +Las diferentes combinaciones reflejan diferentes grados de seguridad y resistencia. El objetivo es permitir la flexibilidad: Por ejemplo, un juego móvil puede no requerir controles de seguridad MASVS
```suggestion
Las diferentes combinaciones reflejan diferentes grados de seguridad y resistencia. El objetivo es permitir la flexibilidad: por ejemplo, un juego móvil puede no requerir controles de seguridad MASVS-L2, como la autenticación de doble factor por razones de usabilidad, pero seguramente deba intentar prevenir la manipulación del código por razones de negocio.
```

2022-08-27 09:29 UTC, cpholguera commented on Document-es/0x03-Using_the_MASVS.md
>  - Sector Financiero: Aplicaciones que permiten el acceso a información altamente sensible como números de tarjetas de crédito, información personal o que permiten al usuario mover fondos. Estas aplic
```suggestion
- Industria de la Salud: aplicaciones móviles que almacenan información personal identificable que puede ser utilizada para el robo de identidad, pagos fraudulentos, o una variedad de esquemas de fraude. Para el sector de la salud en los Estados Unidos, las consideraciones de cumplimiento incluyen la Ley de Portabilidad y Responsabilidad del Seguro Médico (HIPAA, por sus siglas en inglés), Privacidad, Seguridad, Reglas de Notificación de Violación (Breach Notification Rules) y Reglas de Seguridad del Paciente (Patient Safety Rule).

- Sector Financiero: aplicaciones que permiten el acceso a información altamente sensible como números de tarjetas de crédito, información personal o que permiten al usuario mover fondos. Estas aplicaciones deben tener controles de seguridad adicionales para prevenir el fraude. Las aplicaciones financieras necesitan asegurar el cumplimiento de las normas de seguridad de datos de la industria de tarjetas de pago (PCI DSS), Gramm Leech Bliley Act y Sarbanes-Oxley Act (SOX).
```

2022-08-27 09:29 UTC, cpholguera commented on Document-es/0x03-Using_the_MASVS.md
> +- Industria de los videojuegos: Aquellos con una necesidad esencial de evitar la posibilidad de _modding_ y el engaño, como los videojuegos competitivos _online_. Hacer trampa es un tema importante e
```suggestion
- Industria de los videojuegos: aplicaciones con una necesidad esencial de evitar la posibilidad de _modding_ y el engaño, como los videojuegos competitivos _online_. Hacer trampa es un tema importante en los juegos _online_, ya que una gran cantidad de tramposos conduce a un descontento de la base de jugadores y, en última instancia, puede causar que un juego fracase. MASVS-R proporciona controles básicos contra la manipulación para ayudar a incrementar el esfuerzo que los tramposos deberían realizar.
```

2022-08-27 09:29 UTC, cpholguera commented on Document-es/0x03-Using_the_MASVS.md
> +- Industria Financiera: Aplicaciones de banca móvil que permiten al usuario mover fondos, donde las técnicas de inyección de código e instrumentación en dispositivos comprometidos suponen un riesgo.
```suggestion
- Industria Financiera: aplicaciones de banca móvil que permiten al usuario mover fondos, donde las técnicas de inyección de código e instrumentación en dispositivos comprometidos suponen un riesgo. En este caso, los controles MASVS-R se pueden utilizar para dificultar la manipulación de código, dificultando el trabajo de potenciales autores de _malware_.
```

2022-08-27 09:29 UTC, cpholguera commented on Document-es/0x04-Assessment_and_Certification.md
> +Se recomienda el uso de escáneres de código fuente y herramientas de auditoría de tipo _black-box_ para aumentar la eficiencia siempre que sea posible. Sin embargo, no es posible completar la verific
```suggestion
Se recomienda el uso de escáneres de código fuente y herramientas de auditoría de tipo _black-box_ para aumentar la eficiencia siempre que sea posible. Sin embargo, no es posible completar la verificación MASVS utilizando únicamente herramientas automatizadas: cada aplicación móvil es diferente. Por tanto, la comprensión de la arquitectura general, la lógica de negocio y los problemas específicos de las tecnologías y plataformas que se utilizan es un requerimiento obligatorio para verificar la seguridad de la aplicación.
```

2022-08-27 09:29 UTC, cpholguera commented on Document-es/0x07-V2-Data_Storage_and_Privacy_requirements.md
> +- Datos altamente confidenciales que, en caso de que ser comprometidos, ocasionarían daños a la reputación y/o costes financieros: Información contractual, información cubierta por acuerdos de confid
```suggestion
- Datos altamente confidenciales que, en caso de que ser comprometidos, ocasionarían daños a la reputación y/o costes financieros: información contractual, información cubierta por acuerdos de confidencialidad, información de gestión.
```

2022-08-27 09:29 UTC, cpholguera commented on Document-es/0x09-V4-Authentication_and_Session_Management_Requirements.md
> +| **4.6** | MSTG-AUTH-6 | El servidor debe implementar mecanismos cuando se excede un determinado número de intentos de inicio de sesión. Es decir, cuando se introducen erroneamente las credenciales
No podemos cambiarlo tanto respecto al original en inglés. Qué te parece esto?

```suggestion
| **4.6** | MSTG-AUTH-6 | El servidor debe implementar mecanismos que eviten excesivos de intentos de inicio de sesión. | x | x |
```

2022-08-27 09:29 UTC, cpholguera commented on Document-es/0x09-V4-Authentication_and_Session_Management_Requirements.md
> +| **4.9** | MSTG-AUTH-9 | En el dispositivo final debe existir un mecanismo de segundo factor de autenticación (2FA) y éste debe ser consistente. |   | x |
```suggestion
| **4.9** | MSTG-AUTH-9 | En el servidor debe existir un mecanismo de segundo factor de autenticación (2FA) y éste debe ser aplicado de forma consistente. |   | x |
```

2022-08-27 09:29 UTC, cpholguera commented on Document-es/0x10-V5-Network_communication_requirements.md
> +| **5.3** | MSTG-NETWORK-3 | La aplicación debe verificar el certificado X.509 del sistema remoto al establecer el canal seguro y sólo se deben aceptar certificados firmados por una entidad certifica
```suggestion
| **5.3** | MSTG-NETWORK-3 | La aplicación debe verificar el certificado X.509 del sistema remoto al establecer el canal seguro y sólo se deben aceptar certificados firmados por una autoridad certificadora (CA) de confianza. | x | x |
```

2022-08-27 09:29 UTC, cpholguera commented on Document-es/0x10-V5-Network_communication_requirements.md
> +| **5.4** | MSTG-NETWORK-4 | La aplicación debe utilizar su propio almacén de certificados o realiza _pinning_ del certificado o la clave pública del servidor. Bajo ningún concepto establecerá conexi
```suggestion
| **5.4** | MSTG-NETWORK-4 | La aplicación debe utilizar su propio almacén de certificados o realiza _pinning_ del certificado o la clave pública del servidor. Bajo ningún concepto establecerá conexiones con servidores que ofrecen otros certificados o claves, incluso si están firmados por una autoridad certificadora (CA) de confianza. |   | x |
```

2022-08-27 09:29 UTC, cpholguera commented on Document-es/0x11-V6-Interaction_with_the_environment.md
> +| **6.6** | MSTG-PLATFORM-6 | Las WebViews se deben configurar para permitir el mínimo número de protocolos requeridos (idealmente sólo https). Aquellos considerados como peligrosos deben estar desha
```suggestion
| **6.6** | MSTG-PLATFORM-6 | Las WebViews se deben configurar para permitir el mínimo número de protocolos requeridos (idealmente sólo https). Aquellos considerados como peligrosos deben estar deshabilitados (p. ej. file, tel y app-id). | x | x |
```

2022-08-27 09:29 UTC, cpholguera commented on Document-es/0x12-V7-Code_quality_and_build_setting_requirements.md
> +| **7.5** | MSTG-CODE-5 | Todos los componentes de terceros (p. ej. librerías y frameworks) se encuentran identificados y sus vulnerabilidades conocidas revisadas. | x | x |
```suggestion
| **7.5** | MSTG-CODE-5 | Todos los componentes de terceros deben ser identificados y revisados en busca de vulnerabilidades comunes. | x | x |
```

2022-08-27 09:29 UTC, cpholguera commented on Document-es/0x12-V7-Code_quality_and_build_setting_requirements.md
> +| **7.9** | MSTG-CODE-9 | Las funcionalidades y las herramientas de seguridad gratuitas deben estar activadas para: La simplificación del código, protección de la pila, soporte PIE y conteo automátic
```suggestion
| **7.9** | MSTG-CODE-9 | Las funcionalidades y las herramientas de seguridad gratuitas deben estar activadas. Esto incluye simplificación del código, protección de la pila, soporte PIE y conteo automático de referencias. | x | x |
```

2022-08-29 08:39 UTC, cpholguera commented on Document-es/0x07-V2-Data_Storage_and_Privacy_requirements.md
> +- Información de identificación personal que puede ser usada para el robo de identidad: Información de la Seguridad Social, números de tarjetas de crédito, números de cuentas bancarias, información m
```suggestion
- Información de identificación personal que puede ser usada para el robo de identidad: información de la Seguridad Social, números de tarjetas de crédito, números de cuentas bancarias, información médica.
```

2022-08-29 08:49 UTC, cpholguera approved these changes
Hi @antoniojturel, I had to restore a couple of resolved items since we really need them in. Many of them were about the use of ":" which require lowercase after it in the cases we're dealing with (see [here](https://www.rae.es/dpd/dos%20puntos) for more info).

Regarding the rest of the changes I really like this new version, thank you very much!

Thanks a lot

2022-08-29 09:00 UTC, antoniojturel commented
This PR is a full in depth review of 13 files, It wasn´t easy but effective step by step, great job @cpholguera !

2022-08-29 09:50 UTC, merged