Upgrading to v2.0.0
OWASP/owasp-masvs pull request #697
Opened 2023-03-04 16:32 UTC by cpholguera

2023-03-28 07:13 UTC, sushi2k requested changes

2023-03-28 08:13 UTC, cpholguera commented on Document/06-MASVS-CRYPTO.md
> +
```suggestion
```

2023-03-31 06:33 UTC, TheDauntless commented on Document/09-MASVS-PLATFORM.md
> +This category comprises controls that ensure the app's interactions with the mobile platform occur securely. These controls cover the secure use of platform-provided IPC mechanisms, WebView configura
```suggestion
This category comprises controls that ensure the app's interactions with the mobile platform occur securely. These controls cover the secure use of platform-provided IPC mechanisms, WebView configurations to prevent sensitive data leakage and functionality exposure, and secure display of sensitive data in the app's user interface. By implementing these controls, mobile app developers can safeguard sensitive user information and prevent unauthorized access by attackers.
```

2023-03-31 06:33 UTC, TheDauntless commented on Document/07-MASVS-AUTH.md
> +The controls in this category aim to ensure that the verified app implements authentication and authorization mechanisms securely, protecting sensitive user information and preventing unauthorized ac
```suggestion
The controls in this category aim to ensure that the app implements authentication and authorization mechanisms securely, protecting sensitive user information and preventing unauthorized access. It is important to note that the security of the remote endpoint should also be validated using industry standards such as the [OWASP Application Security Verification Standard (ASVS)](https://owasp.org/www-project-application-security-verification-standard/).
```

2023-03-31 06:33 UTC, TheDauntless commented on controls/MASVS-AUTH-3.md
> +Some additional form of authentication is often desirable for sensitive actions inside the app. This can be done in different ways (biometric, pin, MFA code generator, email, deep links, etc) and all
```suggestion
Some additional form of authentication is often desirable for sensitive actions inside the app. This can be done in different ways (biometric, pin, MFA code generator, email, deep links, etc) and they all need to be implemented securely.
```

2023-03-31 06:54 UTC, sushi2k approved these changes

2023-03-31 07:57 UTC, merged